echo "Compiling Esercizio 1.1...";
javac -d ./Esercizio\ 1.1/out/ ./Esercizio\ 1.1/src/*.java || exit;
echo "Compiling Esercizio 1.2...";
javac -d ./Esercizio\ 1.2/out/ ./Esercizio\ 1.2/src/*.java || exit;
echo "Compiling Esercizio 1.3...";
javac -d ./Esercizio\ 1.3/out/ ./Esercizio\ 1.3/src/*.java || exit;
echo "Compiling Esercizio 1.4...";
javac -d ./Esercizio\ 1.4/out/ ./Esercizio\ 1.4/src/*.java || exit;
echo "Compiling Esercizio 1.5...";
javac -d ./Esercizio\ 1.5/out/ ./Esercizio\ 1.5/src/*.java || exit;
echo "Compiling Esercizio 1.6...";
javac -d ./Esercizio\ 1.6/out/ ./Esercizio\ 1.6/src/*.java || exit;
echo "Compiling Esercizio 1.7...";
javac -d ./Esercizio\ 1.7/out/ ./Esercizio\ 1.7/src/*.java || exit;
echo "Compiling Esercizio 1.8...";
javac -d ./Esercizio\ 1.8/out/ ./Esercizio\ 1.8/src/*.java || exit;
echo "Compiling Esercizio 1.9...";
javac -d ./Esercizio\ 1.9/out/ ./Esercizio\ 1.9/src/*.java || exit;
echo "Compiling Esercizio 1.10...";
javac -d ./Esercizio\ 1.10/out/ ./Esercizio\ 1.10/src/*.java || exit;
echo "Compiling Esercizio 1.11...";
javac -d ./Esercizio\ 1.11/out/ ./Esercizio\ 1.11/src/*.java || exit;
echo "All files has been compiled successfully.";
